### ISSUE TITLE
crash on boot

### ISSUE THREAD

**Issue by tajetajea** [Chickenbreadlp/ReboOSt#21]
Whenever i boot the computer after configuring and saving my first time boot settings the computer continuously crashes. And yes, i have tried both the release and dev version
Here is a picture and the computer's data file.
![cc error 1](https://cloud.githubusercontent.com/assets/9670301/14626542/6ee1f8be-05ba-11e6-8270-5dda0435316f.JPG)

[9.zip](https://github.com/Chickenbreadlp/ReboOSt/files/225170/9.zip)

**Comment by Chickenbreadlp** [comment]
Hmm... looks like ReboOSt has a problem with your ComputerCraft Version, because it works fine for me.
Re you running CC 1.76 or newer?

**Comment by Chickenbreadlp** [comment]
I discovered that you need to run CC 1.76 or newer, because ReboOSt uses the ISO 8859-1 Codepage which was fully implemented into CC 1.76.
It looks like you are using CC 1.75 or older. That's why it crashes on startup :/

**Comment by tajetajea** [comment]
Ok thank you
